stages:
  - test

image: python:3.12

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"

before_script:
  - pip install --upgrade pip
  - pip install -r app/requirements.txt

test:
  stage: test
  script:
    - flake8 app || true
    - pytest -q
